//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class leonardc_WebDemoEntities1 : DbContext
    {
        public leonardc_WebDemoEntities1()
            : base("name=leonardc_WebDemoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblStudent> tblStudents { get; set; }
        public virtual DbSet<tblCours> tblCourses { get; set; }
        public virtual DbSet<tblModule> tblModules { get; set; }
        public virtual DbSet<qryStudentGrade> qryStudentGrades { get; set; }
        public virtual DbSet<tblCourseWork> tblCourseWorks { get; set; }
        public virtual DbSet<qryLatestStudentGrade> qryLatestStudentGrades { get; set; }
    }
}
